apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: coderstrust-gateway
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      protocol: HTTP
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-redirect-coderstrust
spec:
  parentRefs:
    - name: coderstrust-gateway
  hostnames:
    - coderstrust.com
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            hostname: coderstrust.global
            scheme: https
