version: "3"

dotenv: [".env"]

includes:
  sdp: sdp

tasks:
  default:
    cmd: task --list-all
    silent: true

  ecr:login: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 343301376154.dkr.ecr.ap-south-1.amazonaws.com

  format:
    deps: [sdp:format]
