version: "3"

dotenv: [".env"]

includes:
  aws:
    taskfile: aws
    dir: aws

tasks:
  default:
    cmd: task --list-all
    silent: true

  pulumi:org:set-default:
    cmds:
      - echo "Setting default Pulumi organization to - $PULUMI_DEFAULT_ORG"
      - pulumi org set-default $PULUMI_DEFAULT_ORG

  deps:
    deps: 
      - pulumi:org:set-default
      - aws:deps

  format:
    deps: 
      - aws:format

  up:
    cmds: 
      - task deps
      - task aws:up -- -r {{.CLI_ARGS}}

  # miscellanea
  cloc: cloc . --vcs git
  aws:login: aws configure sso --profile default
  ecr:login: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 343301376154.dkr.ecr.ap-south-1.amazonaws.com
  kubeconfig:update:
    dir: aws
    cmd: mkdir -p ~/.kube && pulumi stack -s prod output kubeconfig > ~/.kube/config
    generates: [~/.kube/config]
  argocd:password:
    deps: [kubeconfig:update]
    cmd: kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
  argocd:ui: 
    deps: [kubeconfig:update]
    cmds: 
      - echo "ArgoCD password - $(task argocd:password)"
      - kubectl port-forward svc/argocd-server -n argocd 8080:443
  grafana:ui:
    deps: [kubeconfig:update]
    cmd: kubectl port-forward svc/kube-prometheus-stack-grafana 8081:80 -n monitoring
  hubble:ui: 
    deps: [kubeconfig:update]
    cmd: cilium hubble ui
  k9s: 
    deps: [kubeconfig:update]
    cmd: k9s -A --headless --crumbsless