apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shlink.fullname" . }}-config
  labels:
  {{- include "shlink.labels" . | nindent 4 }}
data:
  DB_DRIVER: {{ .Values.config.dbDriver | quote }}
  DEFAULT_DOMAIN: {{ .Values.config.defaultDomain | quote }}
  IS_HTTPS_ENABLED: {{ .Values.config.isHttpsEnabled | quote }}