apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shlink.fullname" . }}-secret
  labels:
  {{- include "shlink.labels" . | nindent 4 }}
stringData:
  GEOLITE_LICENSE_KEY: {{ required "secret.geoliteLicenseKey is required" .Values.secret.geoliteLicenseKey | quote }}
  INITIAL_API_KEY: {{ required "secret.initialApiKey is required" .Values.secret.initialApiKey | quote }}
type: Opaque