kind: Deployment
apiVersion: apps/v1
metadata:
    name: hello-world
spec:
    replicas: 1
    selector:
        matchLabels:
            app: hello-world
    template:
        metadata:
            labels:
                app: hello-world
        spec:
            containers:
                - name: hello-world
                  image: 'nginx:latest'
                  ports:
                      - containerPort: 80
