kind: Deployment
apiVersion: apps/v1
metadata:
    name: hello-world
spec:
    replicas: 1
    selector:
        matchLabels:
            app: hello-world
    template:
        metadata:
            labels:
                app: hello-world
        spec:
            containers:
                - name: hello-world
                  image: 'nginx:latest'
                  ports:
                      - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
    name: hello-world
spec:
    selector:
        app: hello-world
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
    name: hello-world
spec:
    rules:
        - host: hello-world.local
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: hello-world
                            port:
                                number: 80
