version: '3'

tasks:
  deps:
    cmd: pulumi install

  format:
    deps: [deps]
    cmd: pnpm run format

  up:
    deps: [deps]
    env:
      PULUMI_K8S_ENABLE_SERVER_SIDE_APPLY: true
    cmd: pulumi up -s prod {{.CLI_ARGS}}
