// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi'
import * as inputs from '../types/input'
import * as outputs from '../types/output'

import { ObjectMeta } from '../meta/v1'

export namespace argoproj {
  export namespace v1alpha1 {
    /**
     * AppProjectSpec is the specification of an AppProject
     */
    export interface AppProjectSpec {
      /**
       * ClusterResourceBlacklist contains list of blacklisted cluster level resources
       */
      clusterResourceBlacklist?: outputs.argoproj.v1alpha1.AppProjectSpecClusterResourceBlacklist[]
      /**
       * ClusterResourceWhitelist contains list of whitelisted cluster level resources
       */
      clusterResourceWhitelist?: outputs.argoproj.v1alpha1.AppProjectSpecClusterResourceWhitelist[]
      /**
       * Description contains optional project description
       */
      description?: string
      /**
       * Destinations contains list of destinations available for deployment
       */
      destinations?: outputs.argoproj.v1alpha1.AppProjectSpecDestinations[]
      /**
       * NamespaceResourceBlacklist contains list of blacklisted namespace level resources
       */
      namespaceResourceBlacklist?: outputs.argoproj.v1alpha1.AppProjectSpecNamespaceResourceBlacklist[]
      /**
       * NamespaceResourceWhitelist contains list of whitelisted namespace level resources
       */
      namespaceResourceWhitelist?: outputs.argoproj.v1alpha1.AppProjectSpecNamespaceResourceWhitelist[]
      /**
       * OrphanedResources specifies if controller should monitor orphaned resources of apps in this project
       */
      orphanedResources?: outputs.argoproj.v1alpha1.AppProjectSpecOrphanedResources
      /**
       * PermitOnlyProjectScopedClusters determines whether destinations can only reference clusters which are project-scoped
       */
      permitOnlyProjectScopedClusters?: boolean
      /**
       * Roles are user defined RBAC roles associated with this project
       */
      roles?: outputs.argoproj.v1alpha1.AppProjectSpecRoles[]
      /**
       * SignatureKeys contains a list of PGP key IDs that commits in Git must be signed with in order to be allowed for sync
       */
      signatureKeys?: outputs.argoproj.v1alpha1.AppProjectSpecSignatureKeys[]
      /**
       * SourceNamespaces defines the namespaces application resources are allowed to be created in
       */
      sourceNamespaces?: string[]
      /**
       * SourceRepos contains list of repository URLs which can be used for deployment
       */
      sourceRepos?: string[]
      /**
       * SyncWindows controls when syncs can be run for apps in this project
       */
      syncWindows?: outputs.argoproj.v1alpha1.AppProjectSpecSyncWindows[]
    }

    /**
     * GroupKind specifies a Group and a Kind, but does not force a version.  This is useful for identifying concepts during lookup stages without having partially valid types
     */
    export interface AppProjectSpecClusterResourceBlacklist {
      group: string
      kind: string
    }

    /**
     * GroupKind specifies a Group and a Kind, but does not force a version.  This is useful for identifying concepts during lookup stages without having partially valid types
     */
    export interface AppProjectSpecClusterResourceWhitelist {
      group: string
      kind: string
    }

    /**
     * ApplicationDestination holds information about the application's destination
     */
    export interface AppProjectSpecDestinations {
      /**
       * Name is an alternate way of specifying the target cluster by its symbolic name. This must be set if Server is not set.
       */
      name?: string
      /**
       * Namespace specifies the target namespace for the application's resources. The namespace will only be set for namespace-scoped resources that have not set a value for .metadata.namespace
       */
      namespace?: string
      /**
       * Server specifies the URL of the target cluster's Kubernetes control plane API. This must be set if Name is not set.
       */
      server?: string
    }

    /**
     * GroupKind specifies a Group and a Kind, but does not force a version.  This is useful for identifying concepts during lookup stages without having partially valid types
     */
    export interface AppProjectSpecNamespaceResourceBlacklist {
      group: string
      kind: string
    }

    /**
     * GroupKind specifies a Group and a Kind, but does not force a version.  This is useful for identifying concepts during lookup stages without having partially valid types
     */
    export interface AppProjectSpecNamespaceResourceWhitelist {
      group: string
      kind: string
    }

    /**
     * OrphanedResources specifies if controller should monitor orphaned resources of apps in this project
     */
    export interface AppProjectSpecOrphanedResources {
      /**
       * Ignore contains a list of resources that are to be excluded from orphaned resources monitoring
       */
      ignore?: outputs.argoproj.v1alpha1.AppProjectSpecOrphanedResourcesIgnore[]
      /**
       * Warn indicates if warning condition should be created for apps which have orphaned resources
       */
      warn?: boolean
    }

    /**
     * OrphanedResourceKey is a reference to a resource to be ignored from
     */
    export interface AppProjectSpecOrphanedResourcesIgnore {
      group?: string
      kind?: string
      name?: string
    }

    /**
     * ProjectRole represents a role that has access to a project
     */
    export interface AppProjectSpecRoles {
      /**
       * Description is a description of the role
       */
      description?: string
      /**
       * Groups are a list of OIDC group claims bound to this role
       */
      groups?: string[]
      /**
       * JWTTokens are a list of generated JWT tokens bound to this role
       */
      jwtTokens?: outputs.argoproj.v1alpha1.AppProjectSpecRolesJwtTokens[]
      /**
       * Name is a name for this role
       */
      name: string
      /**
       * Policies Stores a list of casbin formatted strings that define access policies for the role in the project
       */
      policies?: string[]
    }

    /**
     * JWTToken holds the issuedAt and expiresAt values of a token
     */
    export interface AppProjectSpecRolesJwtTokens {
      exp?: number
      iat: number
      id?: string
    }

    /**
     * SignatureKey is the specification of a key required to verify commit signatures with
     */
    export interface AppProjectSpecSignatureKeys {
      /**
       * The ID of the key in hexadecimal notation
       */
      keyID: string
    }

    /**
     * SyncWindow contains the kind, time, duration and attributes that are used to assign the syncWindows to apps
     */
    export interface AppProjectSpecSyncWindows {
      /**
       * Applications contains a list of applications that the window will apply to
       */
      applications?: string[]
      /**
       * Clusters contains a list of clusters that the window will apply to
       */
      clusters?: string[]
      /**
       * Duration is the amount of time the sync window will be open
       */
      duration?: string
      /**
       * Kind defines if the window allows or blocks syncs
       */
      kind?: string
      /**
       * ManualSync enables manual syncs when they would otherwise be blocked
       */
      manualSync?: boolean
      /**
       * Namespaces contains a list of namespaces that the window will apply to
       */
      namespaces?: string[]
      /**
       * Schedule is the time the window will begin, specified in cron format
       */
      schedule?: string
      /**
       * TimeZone of the sync that will be applied to the schedule
       */
      timeZone?: string
    }

    /**
     * AppProjectStatus contains status information for AppProject CRs
     */
    export interface AppProjectStatus {
      /**
       * JWTTokensByRole contains a list of JWT tokens issued for a given role
       */
      jwtTokensByRole?: { [key: string]: outputs.argoproj.v1alpha1.AppProjectStatusJwtTokensByRole }
    }

    /**
     * JWTTokens represents a list of JWT tokens
     */
    export interface AppProjectStatusJwtTokensByRole {
      items?: outputs.argoproj.v1alpha1.AppProjectStatusJwtTokensByRoleItems[]
    }

    /**
     * JWTToken holds the issuedAt and expiresAt values of a token
     */
    export interface AppProjectStatusJwtTokensByRoleItems {
      exp?: number
      iat: number
      id?: string
    }
  }
}
