apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "2048"
  namespace: argocd
spec:
  destination:
    namespace: miscellaneous
    server: https://kubernetes.default.svc
  project: sdp
  source:
    path: sdp/resources/app-2048
    repoURL: https://github.com/audacioustux/zeroaws
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - FailOnSharedResource=true
    - CreateNamespace=true
