apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-2048
  namespace: argocd
spec:
  destination:
    namespace: miscellaneous
    server: https://kubernetes.default.svc
  project: sdp
  source:
    path: sdp/resources/game-2048
    repoURL: https://github.com/audacioustux/zeroaws
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
