kind: Deployment
apiVersion: apps/v1
metadata:
    name: app-2048
spec:
    replicas: 1
    selector:
        matchLabels:
            app: app-2048
    template:
        metadata:
            labels:
                app: app-2048
        spec:
            containers:
                - name: game-2048
                  image: 'amigoscode/2048:latest'
                  ports:
                      - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
    name: app-2048
spec:
    selector:
        app: app-2048
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
    name: app-2048
spec:
    rules:
        - host: app-2048.local
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: app-2048
                            port:
                                number: 80
